# Generated by Django 2.2.14 on 2020-07-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200709_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesnhjh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgjh', models.BigIntegerField()),
            ],
        ),
    ]
